### ISSUE TITLE
assetfs 模版绑定失败。模版缺失问题的解决方法。

### ISSUE THREAD

**Issue by robert7git** [dfang/qor-issues#21]
# assetfs 模版绑定失败解决。
经常出现模版缺失问题的解决方法。

也适用于二进制的绑定。

### 再现条件
1. go mod 模式去跑
2. /project/vendor/下 没有  qor 相关包 。
3. gopath/src/ 下 没有 qor 相关包。
就会报错了。

最明显的症状是 开首页，头部显示 action_bar.tmpl 缺失。

### 分析
qor/admin 中 查找模版的步骤是:  
1. 先找 `vendor/`，  
2. 再找 `${GOpath}/src/`

#### 解决方法 1 - 此为下策

修改 qor/admin/admin.go RegisterViewPath 方法.
qor/admin/admin.go

因为觉得能力有限，写的实在是不够优雅。
这里只举例子。

```go
func (admin *Admin) RegisterViewPath(pth string) {  
    if(vendor){
       // some ...
       realPath := ${youprojectPath} + "/vendor/" + pth 
       admin.AssetFS.RegisterPath(realPath)
       // some ...
    }else if(mod)
       // some ...
       // 拼接出 
       realPath := ${gopath}/mod/pkg + pth 
       admin.AssetFS.RegisterPath(realPath)
      // some ...
   }else if(你希望的条件)
      // some ...
      admin.AssetFS.RegisterPath(pth)
     // some ...
   }else{
      fmt.Println("没有匹配到 模版路径")
   }
}
```

#### 解决方法 2 - 此为上策

就是在
project/main.go 中
调用 admin.New(config{
   assetFs: xxx /// 这里 继承 qor/assetsfs 包中的 接口。
})

这个也不好多说了，
能力没到嘛，不然也不会动手改源码了。
但是这是优雅解决的方法，无疑了。

## 另外

强烈建议 删掉 gopath/src 目录。如果你不介意.
除非你对环境很了解，而且明确知道自己在做什么。
否则，最好是把 gopath/src 目录删掉。

why?
比如，你的 gopath 下有 qor 相关源码时。
qor 会读取。
这时，你如果部署线上，而且你用 go mod 模式跑,
hh，可想而知结果，肯定是找不到模版啦。
你的本地开发环境成功运行完全是假象呀。

当找不到头绪时，尽量收窄影响范围是不错的解决问题的思路。

另外，QOR 作者，jinzhu 是坏人😊 joking.

代码写的不错的坏人😊 joking。

**Comment by robert7git** [comment]
@dfang

**Comment by dfang** [comment]
看我整理的wiki
